### ISSUE TITLE
Links are not hidden from non-logged in users completely!

### ISSUE THREAD

**Issue by MeowMeowVenom** [jslirola/flarum-ext-login2seeplus#14] opened 2021-08-16 03:19 UTC
When  you are logged out, in the inspect element area of the site, all the links are visible in the following script tag
```
script type="application/ld+json"
```

**Comment by jslirola** [comment] 2021-09-07 16:31
Sorry for the late response, I haven't been able to reproduce it. Do you have an example? Are you using the latest version of the extension?

My test:

![imagen](https://user-images.githubusercontent.com/6697559/132379548-c18e26fa-9a69-4f3a-be2d-d69806ff3ea9.png)

> <script type="application/ld+json">[{"@context":"http:\/\/schema.org","@type":"DiscussionForumPosting","publisher":{"@type":"Organization","name":"Flarum 1.0","url":"http:\/\/flarum.local","description":"Forum description.","logo":null},"headline":"my discussion","datePublished":"2021-09-07T16:08:40+00:00","description":"this is my message title link","dateModified":"2021-09-07T16:25:25+00:00","url":"http:\/\/flarum.local\/d\/102-my-discussion","author":{"@type":"Person","name":"jslirola","url":"http:\/\/flarum.local\/u\/jslirola"}},{"@context":"http:\/\/schema.org","@type":"WebSite","url":"http:\/\/flarum.local\/","potentialAction":{"@type":"SearchAction","target":"http:\/\/flarum.local\/?q={search_term_string}","query-input":"required name=search_term_string"}}]</script>

**Comment by jslirola** [comment] 2021-09-08 17:33
It could be caused by other extension. If you don't mind, run the command `php flarum info` and show me the output to see what extensions are you using and their versions.

**Comment by Rejected-Peice** [comment] 2021-09-08 23:40
```
Flarum core 1.0.4
PHP version: 8.0.9
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, exif, msgpack, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, snmp, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, memcached, Zend OPcache
+------------------------------------------+---------+--------+
| Flarum Extensions                        |         |        |
+------------------------------------------+---------+--------+
| ID                                       | Version | Commit |
+------------------------------------------+---------+--------+
| flarum-flags                             | v1.0.0  |        |
| flarum-nicknames                         | v1.0.0  |        |
| flarum-tags                              | v1.0.3  |        |
| michaelbelgium-discussion-views          | v7.0.0  |        |
| flarum-sticky                            | v1.0.0  |        |
| fof-spamblock                            | 1.0.0   |        |
| flarum-approval                          | v1.0.0  |        |
| flarum-suspend                           | v1.0.0  |        |
| askvortsov-auto-moderator                | v0.1.1  |        |
| fof-username-request                     | 1.0.0   |        |
| dem13n-discussion-cards                  | 0.3.8   |        |
| clarkwinkelmann-popular-discussion-badge | 1.0.0   |        |
| migratetoflarum-canonical                | 1.0.0   |        |
| opendir-font-awesome-6                   | 1.1     |        |
| justoverclock-username-blacklist         | 0.1.0   |        |
| the-turk-stickiest                       | 2.0.3   |        |
| katosdev-signature                       | 1.1.2   |        |
| the-turk-quiet-edits                     | 0.1.3   |        |
| sycho-profile-cover                      | v1.3.0  |        |
| the-turk-miserable-users                 | 1.0.2   |        |
| askvortsov-markdown-tables               | v1.2.1  |        |
| ianm-level-ranks                         | 1.0.0   |        |
| justoverclock-hashtag                    | 0.1.9   |        |
| glowingblue-password-strength            | 3.0.0   |        |
| fof-stopforumspam                        | 1.0.0   |        |
| fof-sitemap                              | 1.0.0   |        |
| fof-profile-image-crop                   | 1.0.0   |        |
| fof-merge-discussions                    | 1.0.0   |        |
| fof-drafts                               | 1.0.1   |        |
| fof-ban-ips                              | 1.0.0   |        |
| nyu8-email-filter                        | 1.0.5   |        |
| the-turk-diff                            | 1.1.1   |        |
| noriods-auto-more                        | v1.0.0  |        |
| acpl-mobile-tab                          | 1.0.5   |        |
| flarum-bbcode                            | v1.0.0  |        |
| flarum-emoji                             | v1.0.0  |        |
| flarum-lang-english                      | v1.0.0  |        |
| flarum-likes                             | v1.0.0  |        |
| flarum-lock                              | v1.0.0  |        |
| flarum-mentions                          | v1.0.0  |        |
| flarum-statistics                        | v1.0.0  |        |
| flarum-subscriptions                     | v1.0.0  |        |
| clarkwinkelmann-group-list               | 1.0.0   |        |
| ramesh-dada-bbcode-alerts                | 6.21    |        |
| nearata-copy-code-to-clipboard           | v2.0.0  |        |
| flarumite-simple-spoilers                | 1.0.0   |        |
| fof-best-answer                          | 1.0.1   |        |
| fof-html-errors                          | 1.0.0   |        |
| fof-moderator-notes                      | 1.0.0   |        |
| fof-polls                                | 1.0.3   |        |
| fof-pwned-passwords                      | 1.0.0   |        |
| fof-user-bio                             | 1.0.0   |        |
| jslirola-login2seeplus                   | v0.2    |        |
| ianm-no-meta-title                       | 1.0.1   |        |
| justoverclock-purify                     | 0.1.6   |        |
| the-turk-nodp                            | 1.0.1   |        |
| clarkwinkelmann-shadow-ban               | 1.0.2   |        |
| dem13n-topic-starter-label               | 0.1.7   |        |
| extiverse-mercury                        | 0.1.3   |        |
| fof-formatting                           | 1.0.0   |        |
| v17development-seo                       | v1.8.0  |        |
| flarum-markdown                          | v1.0.1  |        |
| fof-upload                               | 1.0.2   |        |
| afrux-asirem                             | v0.1.3  |        |
| v17development-user-badges               | v0.2.1  |        |
| fof-user-directory                       | 1.0.2   |        |
+------------------------------------------+---------+--------+

```

**Comment by jslirola** [comment] 2021-09-09 19:48
I found the culprit finally. There is a conflict with the SEO extension, if you enable the following feature then it will generate extra information for search engines to index it.

![imagen](https://user-images.githubusercontent.com/6697559/132751653-63373aee-70e2-49aa-ade5-721ba6b2ec7b.png)

I'm not sure how to add support for that as the other extension is rendering the content outside of the body. I'll add an issue for now, but I won't set a timeline until I discover some progress on this.

**Comment by Rejected-Peice** [comment] 2021-09-13 02:34
That is not the exact culprit.
The main issue is SEO extension making meta tags (which we cant control).
I disabled the crawl settings and saw no change. Disabling the extension masked the link very well.

**Comment by jslirola** [comment] 2023-04-04 19:10
We can assume that once the compatibility issue is fixed, this will not be a problem. I close this one and I will continue in the other one, when I get some progress

**Closed by jslirola** 2023-04-04 19:10 UTC
