### ISSUE TITLE
Set exceeding length to 0 hides content from all users

### ISSUE THREAD

**Issue by MattyWjeisz** [jslirola/flarum-ext-login2seeplus#20] opened 2022-08-19 11:46 UTC
If setting 'exceeding limit' to 0, content is hidden from all users - including those logged in as well as administrators and moderators. 

Noticed on Flarum 1.4.1 and PHP1.8.1.

![screencapture-owdforum-d-1-owd-guidelines-2022-08-19-21_48_48](https://user-images.githubusercontent.com/111574581/185612298-8ee90458-f6d1-4e74-b06f-af20d056e9ff.png)

**Comment by MattyWjeisz** [comment] 2022-08-20 01:24
Have also noticed same error even when setting exceed length to 1.

**Comment by jslirola** [comment] 2022-08-22 18:25
I'm very busy these weeks, I'll try to take a look as soon as possible. Perhaps the problem is due to the last update of the extension, in the previous version it was working fine for you?

**Comment by MattyWjeisz** [comment] 2022-08-23 01:16
> I'm very busy these weeks, I'll try to take a look as soon as possible. Perhaps the problem is due to the last update of the extension, in the previous version it was working fine for you?

I've only run this extension on the latest version 1.4.1. so I haven't used an earlier version of the extension. If I knew more about it I'd try to find the problem for you, but coding isn't my strong suit unfortunately :(

**Comment by jslirola** [comment] 2022-08-25 12:16
I'm not able to reproduce the issue unless the user's email isn't confirmed.

https://github.com/jslirola/flarum-ext-login2seeplus/blob/14257e206a02655732e03f989eef0516c8e5697b/src/HideContentInPosts.php#L24

Could you check your database and make sure the column is_email_confirmed is 1? Or edit the aboveline and replace it by:

```
if (!$serializer->getActor()->isGuest() /*&& $serializer->getActor()->is_email_confirmed === 1*/)
```

**Comment by jslirola** [comment] 2023-04-17 06:10
Considering the time that has passed since it was reported and there have been no news or other users reporting this, I close the issue. If it happens again, we reopen it to continue the investigation.

**Closed as completed by jslirola** 2023-04-17 06:10 UTC
Labels: invalid
